### PR TITLE
Fix for "Cannot read properties of undefined (reading 'map')" when merge requests disabled for project

### PR DESCRIPTION
**Pull request by ryharrin**
https://github.com/loblaw-sre/backstage-plugin-gitlab/issues/38

I was unable to test this locally as I was getting a lot of react-hook errors when I used 'yarn link', but this seems like the simplest fix for the issue.

### CODE REVIEW

**Comment by tomwolfgang** [comment]
Any chance to get this approved?

**Comment by satrox28** [comment]
thanks for making the changes @ryharrin, its approved and  merged @tomwolfgang

**Review by satrox28 — APPROVED** [review]

**Comment by satrox28** [comment]
@ryharrin can you  check and sign the commit. https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by ryharrin** [comment]
@satrox28 - sorry about that!

**Review by satrox28 — APPROVED** [review]
change looks good

**Comment by satrox28** [comment]
Hi, can you check on rebase the code @ryharrin, thank you.

**Review by satrox28 — APPROVED** [review]
change looks good

**Pull request merged**
