### PR TITLE
Add support to backstage v1.6.0 & remove unnecessary react-router dep

### PR DESCRIPTION
**Pull request by ivangonzalezacuna**
Added support to the latest version of backstage.

This change is really important, and many people might face issues upgrading their plugin in the near future.

Also, I removed the `react-router` dependency and, consequently, a few lines in the `Router.ts` file, as this is not needed to display the `GitlabCi` component.

### CODE REVIEW

**Review by NishkarshRaj — APPROVED** [review]

**Comment by NishkarshRaj** [comment]
@satrox28 this is very important for any adopter to perform: https://backstage.io/docs/tutorials/react-router-stable-migration if they are using GitLab Plugin.

**Comment by FlxPeters** [comment]
Any news on this? We have the same issue and i would like to update to the current backstage version. 
Thanks for your PR @ivangonzalezacuna!

**Comment by satrox28** [comment]
@richardmcsong please take a look.

**Comment by ivangonzalezacuna** [comment]
Hi. Any update on this? We would really like to get rid of the beta version of react router and update to the latest version of backstage (1.7.0 already)

**Comment by djetelina** [comment]
Let me bump this, as I started playing around with backstage starting with 1.6.0, this plugin never worked for me. Does Loblaw plan to maintain the plugin, or should the community start thinking about a fork?

**Comment by testn** [comment]
@satrox28 Would you mind help looking into this issue?

**Comment by AlexPerkbox** [comment]
Can anyone approve this please? It is blocking gitlab's integration in backstage's newest release.

**Comment by xuanyue202** [comment]
As a workaround, I created a mimic lib tested with backstage v1.8.0. You can use this lib before the official one get updated.

https://www.npmjs.com/package/backstage-plugin-gitlab

**Comment by satrox28** [comment]
Hi All,

I am no longer with the Organization, have informed the required folks, please allow sometime time for them to respond here.

**Comment by devops-systems-com** [comment]
> As a workaround, I created a mimic lib tested with backstage v1.8.0. You can use this lib while waiting for the official one to be updated.
> 
> https://www.npmjs.com/package/backstage-plugin-gitlab
Please can you provide a link to the mimic lib as the posted link just goes back to the same broken version by loblaw

**Comment by sbarrypoppulo** [comment]
Is it possible to get this PR reviewed and merged so latest package is published and can be consumed in Backstage 1.6.0+?

**Comment by JellyBellyDev** [comment]
Hi guys!
not having [received replies and feedback](https://github.com/loblaw-sre/backstage-plugin-gitlab/issues/228), as promised, we forked with the commitment to maintain the plugin more actively.
We hope that the plugin user community will follow and support us.
You can find us at the following links:
https://github.com/immobiliare/backstage-plugin-gitlab
https://www.npmjs.com/package/@immobiliarelabs/backstage-plugin-gitlab
Thanks! 🚀

**Pull request closed without merging**
