### PR TITLE
issue table added

### PR DESCRIPTION
**Pull request by Abhay-soni-developer**
A table to see all the open and closed issues.

### CODE REVIEW

**Comment by NishkarshRaj** [comment]
@satrox28 @Balasundaram  can you please review? Cheers

**Comment by Abhay-soni-developer** [comment]
@pragone @mscam @nikmel2803 please review , Thank you

**Comment by satrox28** [comment]
HI @Abhay-soni-developer 

We can remove the column ISSUE TYPE as its already related to gitlab issues, apart from that changes looks good.

**Comment by Abhay-soni-developer** [comment]
Hi Satish <https://github.com/satrox28>

Yes, I can remove it, but issue_type can have different values, such as
bug, enhancement etc.
so what is your suggestion after this?

Your Thankfully
Abhay Soni

**Comment by satrox28** [comment]
Ya, I checked it @Abhay-soni-developer

**Comment by satrox28** [comment]
You can revert the changes of removing issue_type, it's fine to have it @Abhay-soni-developer

**Comment by Abhay-soni-developer** [comment]
Hi @satrox28 ,
the requested changes have been done.
please go through it and kindly merge it.

Thank you in advance! cheers 🥂 

issue table changed per request

**Comment by Abhay-soni-developer** [comment]
Hey @satrox28,

I have reversed the changes done to remove the issue type. 
can we move ahead with merging ?

Thank you for your efforts @satrox28  😃

**Comment by satrox28** [comment]
@Abhay-soni-developer DCO check is failing, please check it.

**Comment by Abhay-soni-developer** [comment]
> @Abhay-soni-developer DCO check is failing, please check and sign the commits.
> 
> Summary Commit sha: [3583ade](https://github.com/loblaw-sre/backstage-plugin-gitlab/pull/135/commits/3583ade2a4209e72388b57c75753a552ca55127d), Author: Abhay Soni, Committer: Abhay Soni; The sign-off is missing. Commit sha: [8c7a1fb](https://github.com/loblaw-sre/backstage-plugin-gitlab/pull/135/commits/8c7a1fb1475e88133a06962399614799dff57583), Author: Abhay Soni, Committer: Abhay Soni; The sign-off is missing. Commit sha: [b8a0cc4](https://github.com/loblaw-sre/backstage-plugin-gitlab/pull/135/commits/b8a0cc415ede98736c02718dfc7d741c88218876), Author: Abhay Soni, Committer: Abhay Soni; The sign-off is missing.

fixed now, please merge

**Review by satrox28 — APPROVED** [review]
LGTM

**Comment by satrox28** [comment]
I have merged it thanks @Abhay-soni-developer

**Comment by Abhay-soni-developer** [comment]
😃Thank you ***@***.****

**Pull request merged**
