### PR TITLE
added links to merge-request Id

### PR DESCRIPTION
**Pull request by shvmbisht**
Merge request id is now modified to link of the merge request rather than just plain text and clicking on a MR id will open the Gitlab.com page for the MR in a new tab.

### CODE REVIEW

**Review by mufaddal7 — DISMISSED** [review]

**Review by satrox28 — CHANGES_REQUESTED** [review]
Thanks for your contribution. It will be better to have links on the MR Title column rather than on ID's.

**Comment by shvmbisht** [comment]
@satrox28 changes are done as requested.

**Comment by satrox28** [comment]
> @satrox28 changes are done as requested.

looks good, can you rebase the code.

**Comment by shvmbisht** [comment]
Sure

**Comment by satrox28** [comment]
Duplicate PR #10

**Pull request closed without merging**
